language: d

d:
 - dmd

os:
 - linux

# Test step
script:
 - dub build --compiler=${DC}
 - dub build --root=test
 - cd bin && ./beast_testsuite

notifications:
 email:
  on_success: never
  on_failure: always

 irc:
  - irc.freenode.net#beast-lang